# SPDX-FileCopyrightText: 2025 Jacques Supcik <jacques.supcik@hefr.ch>
#
# SPDX-License-Identifier: Apache-2.0 OR MIT

on:
  push:
  pull_request:

jobs:
  docs:
    name: Build documentation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python 3
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Install Poetry
        run: python -m pip install poetry==2.0.1
      - name: Configure poetry
        run: poetry config virtualenvs.in-project true
      - name: Install dependencies
        run: poetry install --with=docs
      - name: Build documentation
        run: poetry run sphinx-build -M html docs public
      - name: Upload pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: public

  # Deploy site to Github pages
  deploy:
    needs: docs
    if: >
      (github.event_name == 'push' && github.ref == 'refs/heads/main') ||
      (github.event_name == 'push' && github.ref == 'tags/*')
    permissions:
      # to deploy to Pages
      pages: write
      # to verify the deployment originates from an appropriate source
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
